chore: upgrade to Tauri 2.0 Beta
impierce/identity-wallet pull request #109
Opened 2024-02-06 13:45 UTC by daniel-mader

# Description of change
Please write a summary of your changes and why you made them.

## Links to any relevant issues
#108 

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-02-09 07:47 UTC, daniel-mader commented
Currently waiting for [this issue](https://github.com/tauri-apps/tauri/pull/8777) being released in the next version (possibly `tauri 2.0.0-beta.3`)

2024-03-20 20:26 UTC, daniel-mader commented
> Currently waiting for [this issue](https://github.com/tauri-apps/tauri/pull/8777) being released in the next version (possibly `tauri 2.0.0-beta.3`)

Got released, so we're clear to update.

2024-03-28 13:57 UTC, nanderstabel approved these changes, later dismissed

2024-03-29 14:01 UTC, Oran-Dan commented on README.md
> +> Before committing, please make sure to run:
add backend tests and formatting as well

2024-03-29 14:06 UTC, Oran-Dan requested changes
just a few lines in the README and it should be good to go

2024-04-02 07:30 UTC, Oran-Dan submitted a review, later dismissed

2024-04-02 07:37 UTC, Oran-Dan submitted a review, later dismissed

2024-04-02 07:44 UTC, Oran-Dan approved these changes

2024-04-02 08:37 UTC, nanderstabel approved these changes

2024-04-02 08:39 UTC, merged