fix: Theming when user is onboarding was not set correctly
impierce/identity-wallet pull request #153
Opened 2024-03-13 14:49 UTC by Norlock

# Description of change
Make theme default (system) because it would be that. However the bug was related to when profile was not set, it wouldn't go into the function because it would be null (see the if guard). However this fix makes sure it will default back to system 

## Links to any relevant issues
Be sure to reference any related issues by adding `fixes issue #`.

## How the change has been tested
Created profiles with system, dark and light, and then reset the profile again.

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-03-14 11:30 UTC, Oran-Dan approved these changes, later dismissed

2024-03-14 13:36 UTC, Oran-Dan approved these changes, later dismissed

2024-03-14 13:56 UTC, nanderstabel commented
Something still seems the be not working correctly here (at least on my device).

This scenario:
1. my phone is in dark mode
2. I start UniMe, it picks up on the system theme which is Dark mode, I just stay in the welcome page :white_check_mark:  
3. I don't close the app, but I change my phone phone to Light mode
4. I go back to UniMe, but it is still in Dark mode :x: 

point 4. used to automatically switch theme (it still did in  `0.4.10`)

2024-03-14 14:18 UTC, daniel-mader requested changes

2024-03-14 14:18 UTC, daniel-mader commented on unime/src/routes/+layout.svelte
> -  systemColorScheme.addEventListener(
By removing this, you remove the listener to window events completely. When the theme is now changed through the OS, it does not have any effect anymore.

2024-03-14 16:53 UTC, daniel-mader commented on unime/src/routes/+layout.svelte
> +  // This is used for detecting the OS theme changes.
I don't think this comment adds any value since the variable is already called `systemColorScheme`.

2024-03-14 16:54 UTC, daniel-mader commented on unime/src/routes/+layout.svelte
> +    // This is used for detecting the theme changes inside the app.
I don't think this comment adds any value since the check is already descriptive: `$state` > `profile_settings` > `theme`.

2024-03-15 08:55 UTC, daniel-mader approved these changes

2024-03-15 09:05 UTC, nanderstabel approved these changes

2024-03-15 09:07 UTC, merged