feat: add support for `ES256`
impierce/identity-wallet pull request #236
Opened 2024-05-21 13:15 UTC by nanderstabel

# Description of change
Please write a summary of your changes and why you made them.

## Links to any relevant issues
Be sure to reference any related issues by adding `fixes issue #`.

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-05-24 13:04 UTC, Norlock requested changes

2024-05-24 13:04 UTC, Norlock commented on Cargo.toml
> +did_manager = { git = "https://github.com/impierce/did-manager.git", rev = "d32ed05" }
Maybe add a git tag to the commit and point to that its much clearer to see what we previously pointed to and what commits happened since then. :)

2024-05-24 13:04 UTC, Norlock commented on identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
> +) -> (String, Option<String>, String, String, Algorithm) {
Can we create a struct for the return type, it will convey its meaning a bit better

2024-05-24 13:04 UTC, Norlock commented on identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
> +            extension: oid4vc::oid4vp::authorization_request::ClientMetadataParameters { vp_formats },
maybe remove some of the part and import it e.g.: `authorization_request::ClientMeta...

2024-05-24 13:04 UTC, Norlock commented on identity-wallet/src/state/profile_settings/reducers/create_new.rs
> +            .identifier("did:key", Algorithm::EdDSA)
Can you make an enum `DidMethod` with variants key, jwk and then add Display trait to it. I think you can pass the enum unless you really need the string in that case you just call .to_string()

2024-05-28 14:00 UTC, daniel-mader commented on Cargo.toml
> +did_manager = { git = "https://github.com/impierce/did-manager.git", rev = "d32ed05" }
That's a good idea. I think we should start doing that once we have proper versioning.

2024-07-23 11:01 UTC, maiertech reviewed
Fine in principle, but let me have a look again after rebasing.

2024-07-23 11:01 UTC, maiertech commented on unime/src/routes/(app)/me/settings/app/did/+page.svelte
> +  $: preferred_did_method = $state.profile_settings.preferred_did_methods.at(0);
Why not `preferredDidMethod`? Trying to understand when to use camel case and when snake case.

2024-07-23 11:01 UTC, maiertech commented on unime/src/routes/(app)/me/settings/app/keys/+page.svelte
> +  $: preferred_key_type = $state.profile_settings.preferred_key_types.at(0);
Same as before: camel case vs. snake case.

2024-07-23 11:01 UTC, maiertech reviewed
Fine in principle, but let me have a look again after rebasing.

2024-07-31 14:26 UTC, nanderstabel commented on unime/src/routes/(app)/me/settings/app/did/+page.svelte
> +  $: preferred_did_method = $state.profile_settings.preferred_did_methods.at(0);
From internal discussion (with @daniel-mader):
> We currently export everything without adhering to TypeScript naming conventions. So this is a Rust string, but as a TypeScript value.
> We will change this eventually once we move to a different bindings library, but I'd leave it for now.

2024-07-31 14:26 UTC, nanderstabel commented on unime/src/routes/(app)/me/settings/app/keys/+page.svelte
> +  $: preferred_key_type = $state.profile_settings.preferred_key_types.at(0);
See above :)

2024-07-31 14:31 UTC, nanderstabel commented
I've rebased this branch (and also fixed a bug where the preferred signing algorithm was not being respected), so it is now finally ready for the final review.

2024-08-05 14:32 UTC, daniel-mader approved these changes

2024-08-06 08:07 UTC, maiertech approved these changes

2024-08-06 08:43 UTC, merged