build(deps): upgrade Tauri from `beta` to `rc`
impierce/identity-wallet pull request #364
Opened 2024-09-03 08:55 UTC by daniel-mader

# Description of change
Please write a summary of your changes and why you made them.

## Links to any relevant issues
- closes #283, #320

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-12-06 14:30 UTC, M-Adam-Hus commented
![](https://github.trello.services/images/mini-trello-icon.png) [build(deps): upgrade Tauri from beta to stable](https://trello.com/c/COpogoJz/75-builddeps-upgrade-tauri-from-beta-to-stable)

2025-02-10 10:12 UTC, maiertech commented
This branch contains a regression in dev mode (dashed lines should be off):

![regression](https://github.com/user-attachments/assets/6311446b-f6fa-4e09-b7de-39d7997e353f)

2025-02-11 14:54 UTC, maiertech commented
<img src="https://github.com/user-attachments/assets/32f8e39a-10ee-4264-b759-e444f71b1a34" width="256" />

UniMe gets stuck on `/` route and does not navigate to `/me`. To reproduce:

1. Run `pnpm tauri ios dev` with iPhone attached via USB.
2. In dev mode turn on Ferris profile.
3. UniMe is stuck on `/`.

2025-02-14 23:08 UTC, nanderstabel commented on identity-wallet/src/state/actions.rs
> +
This placement doesn't really make any sense anymore :sweat_smile: . This TODO message refers to the `mod bindings` block and has nothing to do with the doc comments that are now beneath it. 

I understand that you did this to silence a Clippy warning but I don't think this is the proper solution. 

I believe @Oran-Dan's intention with the code example to demonstrate how different parts of the Redux pattern come together in code (since these parts are (intentionally) separated in our codebase. They're doc comments because this simply adds nice color coding instead of having all code as plain comments.

I think there are (at least) 3 options here (instead of you solution):
1. Change the example from doc comments to 'normal' comments (we will loose the nice color coding though)
2. Move this code example elsewhere, for example to the `mod.rs` file in the same folder some place where it will not cause the same clippy warning (or do this in combination with option 3).
3. Add `#[allow(clippy::empty_line_after_doc_comments)]` above the code example to silence the clippy warning (since even though we care about Clippy Lints, we can still assess where we think its suggestions are suitable and where not. We don't even make use of `cargo docs` at all so I think this is a valid option as well).

Option 2 and 3 can both be used actually.

2025-02-17 15:51 UTC, nanderstabel requested changes
I've thoroughly tested in UniMe and it seems to me that this upgrade fully works. 

The only difference I noticed is that running `cargo tauri dev` in the root of the repository does not work anymore for me. I need to run in it in the `/unime` folder in order for it to work. I'm pretty sure that's due to a change in the Tauri CLI so not relevant to this PR (also, it's not really a hindrance)

2025-02-18 21:24 UTC, daniel-mader commented on identity-wallet/src/state/actions.rs
> +
Option 3 was chosen since moving code examples around is not in scope of this PR

2025-02-19 11:17 UTC, daniel-mader commented
> I've thoroughly tested in UniMe and it seems to me that this upgrade fully works.
> 
> The only difference I noticed is that running `cargo tauri dev` in the root of the repository does not work anymore for me. I need to run in it in the `/unime` folder in order for it to work. I'm pretty sure that's due to a change in the Tauri CLI so not relevant to this PR (also, it's not really a hindrance)

I just checked out the current `dev` branch and tried running `cargo tauri dev` in the root as well and it also doesn't work there for me. This could have already happened when we switched from `npm` to `pnpm` in https://github.com/impierce/identity-wallet/pull/348.

2025-02-20 09:17 UTC, Oran-Dan approved these changes
Everything works smooth, played around quite a bit and also completed the demo flow. ```cargo tauri dev``` from any folder hasn't worked for me since I reinstalled Linux on my laptop. I'm missing some Tauri CLI download I think. But it was never a problem for me since ```pnpm tauri dev``` in the root folder worked for me right from the start, no hassle at all. (I had a lot more hassle first time I installed linux on my then new laptop)

2025-02-20 14:10 UTC, nanderstabel approved these changes
I've tested again extensively (Android) and to me it looks like everything is working as expected. Great upgrade! :partying_face:

2025-02-28 14:27 UTC, merged