fix: support StatusList2021Entry credentials and improve logo fetching from well-known/openid-credential-issuer
impierce/identity-wallet pull request #414
Opened 2024-11-22 08:41 UTC by Oran-Dan

# Description of change
Previously the StatusList2021Entry type credential broke with our code, this is now fixed.
Also the metadata from the well-known is now more thoroughly searched to find the right logo for the credential.

## Links to any relevant issues

## How the change has been tested
- Go to https://omzetbelasting.bd.demo.sphereon.com/
- Create a Omzetbelasting credential by filling in some dummy information
- Click continue and a screen with a qr code will appear
- Below it enter the cuddly-curufin URL
- Now it will continue to a JSON page, copy the `received_offer_id` at the top of the JSON payload on this page.
- Open Postman, make sure your environment variables are set to cuddly-curufin, go to POST `offers_accept`, fill in the `received_offer_id` you just copied and click SEND.
- Now it should return a 200 OK, scroll down to copy the `holder_credential_id` .
- paste this into the POST `presentations` request and click SEND
- Now copy the `presentation_id` and paste this into the `services/linked-vp` and click SEND.
- Go to `siopv2_authorization_requests` and click SEND, copy the QR code string
- Spin up Unime in dev mode, go to "Scan", and paste and process the QR code string
- You should now see the Omzetbelasting credential with logo

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-12-06 11:21 UTC, daniel-mader requested changes

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/resources/default_trust_list.json
> +    "https://agent-dev.impierce.com",
This was removed on purpose in a previous change, because it's outdated.

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +            // This is a fallback to get the url from a did:web to validate domain linkage. This is useful for companies who haven't implemented domain linkage yet.
Please make sure to mark it with a TODO if this is temporary or should be re-evalutated later. If it is intended to stay in the logic, you don't need a TODO.

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        info!("Linkedverifiablecredential: name: {name:?}, logo_uri: {logo_uri:?}, issuance_date: {issuance_date}");
This reads a bit weird: `Linkedverifiablecredential`. Consider Pascal casing or change to just `Linked VP:` _(or similar)_

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        warn!("Failed to get credential_subject: {linked_verifiable_credential:#?}");
Is this message consistent? What is actually logged here? The `credential_subject` or the `linked_verifiable_credential`?

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +        .or_else(|| credential_subject.properties.get("legal_person_name"))
Is this a standardized claim name? If yes, please link the according spec somewhere.

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +/// Then, if no success, we look inside the Credential Configuration Supported and try the match keys in there with the strings in the type array of the credential, in reverse order.
I like the detailled description here!
I had a bit of trouble reading this part:
**[...] and try the match keys in there with the strings in the type array [...]**
Maybe it helps if you wrap actual field names in backticks to indicate a technical term, such as:
**[...] try to match a credential \`type\` (in reverse order).**

2024-12-06 11:21 UTC, daniel-mader commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +        // TODO: this needs to be fixed in the frontend.
If it's a frontend bug, then don't try to "fix" it here by giving it a non-sense URI. I suggest getting rid of the entire `else` branch.

2024-12-06 11:56 UTC, Oran-Dan commented on identity-wallet/resources/default_trust_list.json
> +    "https://agent-dev.impierce.com",
removed

2024-12-06 11:58 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +            // This is a fallback to get the url from a did:web to validate domain linkage. This is useful for companies who haven't implemented domain linkage yet.
added TODO

2024-12-06 11:59 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        info!("Linkedverifiablecredential: name: {name:?}, logo_uri: {logo_uri:?}, issuance_date: {issuance_date}");
Fixed, converted to Pascal

2024-12-06 12:01 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        warn!("Failed to get credential_subject: {linked_verifiable_credential:#?}");
fixed. it was consistent but clarified the text now.

2024-12-06 12:03 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +        .or_else(|| credential_subject.properties.get("legal_person_name"))
fixed

2024-12-06 12:56 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +/// Then, if no success, we look inside the Credential Configuration Supported and try the match keys in there with the strings in the type array of the credential, in reverse order.
fixed

2024-12-06 13:23 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +        // TODO: this needs to be fixed in the frontend.
fixed

2024-12-06 14:27 UTC, M-Adam-Hus commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix: support StatusList2021Entry credentials and improve logo fetching from well-known/openid-credential-issuer](https://trello.com/c/oniYlU0c/71-fix-support-statuslist2021entry-credentials-and-improve-logo-fetching-from-well-known-openid-credential-issuer)

2024-12-06 22:09 UTC, nanderstabel requested changes

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                let options = JwtCredentialValidationOptions::new().status_check(StatusCheck::SkipUnsupported);
I think it would be good to add a comment here to explain why the status check can be skipped

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +async fn get_logo_uri(
General remark: This function has gotten quite bloated and although we don't need to over-optimize this (since we need to come up with a non-custom solution anyway), it is still a good idea to make sure the current code is less bloated, easier to read and of course we need to make sure nothing unexpected can happen.

I will leave several comments throughout the function to highlight things that I think can cause problems and/or could be improved. 

In the final overall comment on this function I will share how I would address these problems altogether (this doesn't mean my suggestion should replace yours, it is just to illustrate an alternative. You can re-implement the code to your liking if you agree with the points I will make).

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        if let Some(image) = display[0].get("logo") {
Indexing like this on a vector or array is dangerous because it will panic if the `display` vector is empty. In the future we should make sure cargo clippy catches this for us using [this lint](https://rust-lang.github.io/rust-clippy/v0.0.212/index.html#indexing_slicing).

The following is a safe way to obtain the image here:
```rust
display.first().and_then(|display| display.get("logo"))
```

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +        match logo_uri_str.parse() {
Two flaws I currently see with this code block though is the following situations:
1.
  * Let's say the value of `logo_uri` is `"not a URI"`?
  * This code block would detect that the value is not a valid `Url` and will therefore make the correct decision not to download the asset.
  * Still, this function will return `Some("not a URI")` and since it is not a `None` value, the frontend will think the backend actually found and persisted a logo.

So since you already validated that the logo could not be downloaded, it would be wise to return `None` if that is the case :)

2. If a `logo_uri` was found in line 359, then it will be downloaded in line 361, and then again in this code block (if `logo_uri` is a valid `Url`).

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        if let Some(image) = display[0].get("logo") {
This may differ person to person, but deeply nested `if let ...` sequences like this make code harder to follow in my opinion. 

I personally prefer using `.and_then()` and `.map()` (functional style) where I can because I think they're easier to follow.

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        }
The logic in both match cases here is basically the same except that in the second case multiple types are being checked. This unnecessary code duplication makes it harder to see what is going on and can be easily prevented.

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                                            break;
While your other two `break` statements will break out of the outer for loop in line 378, this one here will only break out of the for loop in line 416 instead (which I don't think was your intention.

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                                        logo_uri = image_url.as_str().map(ToString::to_string);
This pattern of extracting the `logo_uri` from the `display` property is quite common so perhaps deserves its own separate function.

2024-12-06 22:09 UTC, nanderstabel commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +}
My complete refactor suggestion:

```rust
async fn get_logo_uri(
    credential_subject: &Subject,
    linked_verifiable_credential: &DecodedJwtCredential<Value>,
    validated_linked_domains: &[Url],
) -> Option<String> {
    let mut logo_uri = credential_subject
        .properties
        .get("image")
        .and_then(Value::as_str)
        .map(ToString::to_string);

    // Check if logo URI was retrieved, else attempt to retrieve from well-known endpoint
    if logo_uri.is_none() {
        for domain in validated_linked_domains.iter() {
            let well_known_endpoint = format!("{}.well-known/openid-credential-issuer", domain);
            info!("Trying to fetch image from {well_known_endpoint} endpoint");
            if let Ok(response) = reqwest::Client::new().get(&well_known_endpoint).send().await {
                if let Ok(metadata) = response.json::<CredentialIssuerMetadata>().await {
                    logo_uri = metadata.display.as_deref().and_then(extract_logo_uri_from_display);

                    if logo_uri.is_some() {
                        break;
                    }
                }
            }
            // TODO: Due to mixing 2 specs here, the oid4vci and linked verifiable presentation spec, we lose the Credential Issuer Identifier (CII) during the linked vp flow.
            // The CII tells us where exactly we can add "/.well-known/openid-credential-issuer" to fetch the Credential Issuer Metadata, in which we might find the logo.
            // For now we assume it's the same domain as the linked domain.
            // But this is no guarantee and the code below is one such workaround.
            let well_known_endpoint = format!("{}oid4vci/.well-known/openid-credential-issuer", domain);
            info!("Trying to fetch image from {well_known_endpoint} endpoint");
            if let Ok(response) = reqwest::Client::new().get(&well_known_endpoint).send().await {
                if let Ok(metadata) = response.json::<CredentialIssuerMetadata>().await {
                    logo_uri = linked_verifiable_credential.credential.types.iter().find_map(|type_| {
                        info!("Trying to fetch from Credential Configuration Supported: {}", type_);
                        metadata
                            .credential_configurations_supported
                            .get(type_)
                            .map(|credential_configuration| credential_configuration.display.as_ref())
                            .and_then(extract_logo_uri_from_display)
                    });

                    if logo_uri.is_some() {
                        break;
                    }
                }
            }
        }
    }

    OptionFuture::from(logo_uri.map(|logo_uri| async move {
        info!("Logo URI: `{}`", logo_uri);

        let _ = download_asset(
            logo_uri
                .parse()
                .inspect_err(|parse_err| warn!("Failed to parse logo URI: `{}`, {}", logo_uri, parse_err))
                .ok()?,
            &hash(&logo_uri),
        )
        .await
        .inspect_err(|err| warn!("Failed to download logo URI: {}", err));
        Some(logo_uri.to_string())
    }))
    .await
    .flatten()
}

fn extract_logo_uri_from_display(display: &[Value]) -> Option<String> {
    display
        .first()
        .and_then(|display| display.get("logo"))
        .and_then(|logo| logo.get("uri").or(logo.get("url")))
        .and_then(|url| url.as_str())
        .map(ToString::to_string)
}
```

2024-12-07 09:36 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                let options = JwtCredentialValidationOptions::new().status_check(StatusCheck::SkipUnsupported);
good point, fixed

2024-12-07 10:49 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        if let Some(image) = display[0].get("logo") {
True! we should add these lints asap

2024-12-07 10:50 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +async fn get_logo_uri(
great points, thanks a lot

2024-12-07 10:51 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +        match logo_uri_str.parse() {
fixed

2024-12-07 10:55 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        if let Some(image) = display[0].get("logo") {
agreed

2024-12-07 10:56 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                        }
done

2024-12-07 10:56 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                                            break;
fixed

2024-12-07 10:57 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                                        logo_uri = image_url.as_str().map(ToString::to_string);
Yes, I ended up with your suggestion being the cleanest

2024-12-07 10:58 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +                                            break;
Also used your suggestion here with the `find_map`, nice function otherwise I would have used 2 breaks in a row.

2024-12-07 13:02 UTC, Oran-Dan commented on identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
> +}
So most of your suggestions I agree with and more or less end up with then trying myself. Only the asset downloading I've mostly kept the same as before.

2024-12-09 16:17 UTC, nanderstabel approved these changes

2024-12-09 21:13 UTC, daniel-mader approved these changes

2024-12-10 07:58 UTC, merged