Feat/actiontrait
impierce/identity-wallet pull request #92
Opened 2024-01-12 10:11 UTC by nanderstabel

# Description of change
Please write a summary of your changes and why you made them.

## Links to any relevant issues
Be sure to reference any related issues by adding `fixes issue #`.

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-01-22 22:27 UTC, nanderstabel commented
Closing this PR since it's merged into this PR now: https://github.com/impierce/identity-wallet/pull/102

2024-01-23 21:53 UTC, daniel-mader requested changes

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/state/reducers/mod.rs
> +    if let Some(UpdateProfileSettings { theme, name, picture }) = listen::<UpdateProfileSettings>(action) {
Since all fields in the action are optional (theme, name, picture) and the frontend only provides the field that was changed, you now always reset the profile to default for all values except the actual changed field. Existing fields should keep the same value as in `.replace()`. We should also add a test for it.

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/tests/fixtures/actions/authenticate_connect_accept.json
> +    "payload": null
The tests also run if I remove the `payload` completely. Can we remove `"payload": null` in all test fixtures?

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/command.rs
> +            println!("APP STATE: {app_state:?}\n\n");
Can we modify the print here? We're not modifying console outputs anywhere else in the app through stuff like `\n\n`. Can we use tracing instead like `debug!("{app_state:?}")`?

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/state/actions/mod.rs
> +            payload: Option<GetState>,
Since `GetState` never takes a `payload`, we can also remove it completely, right? I still satisfies the `ActionTrait` and would allow to offer all three types of payloads that can exist: `payload: Foobar` (mandatory), `payload: Option<Foobar>` (optional), no payload at all.

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/state/actions/get_state.rs
> +#[ts(export, export_to = "bindings/actions/GetState.ts")]
No need to export bindings for an empty struct (exported to `export type GetState = null;` which doesn't make sense).

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/state/actions/mod.rs
> +    use crate::state::actions::get_state::GetState;
Why this import?

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/state/actions/mod.rs
> +            payload: Option<LoadDevProfile>,
Payload can be removed entirely here as well

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/src/state/actions/cancel_user_journey.rs
> +#[ts(export, export_to = "bindings/actions/CancelUserJourney.ts")]
All exports by `ts_rs` that produce something like `export type Foobar = null;` can be removed.

2024-01-23 21:53 UTC, daniel-mader commented on src-tauri/identity_wallet/bindings/actions/CancelUserJourney.ts
These types have no real value and are only misleading. I think all bindings similar to this one (`= null;`) should not be generated.

2024-01-23 21:53 UTC, daniel-mader commented on src/routes/prompt/accept-connection/+page.svelte
> +          type: '[Authenticate] Connection accepted'
Please run `npm run format` on the entire project (will be added to a GitHub Action soon)

2024-01-24 14:01 UTC, Norlock commented on src-tauri/identity_wallet/src/state/reducers/user_data_query.rs
> +            }) as Action,
Why as Action here?

2024-01-24 14:01 UTC, Norlock commented on src-tauri/tests/tests/credential_offer.rs
> +use std::sync::Arc;
please always use tokio::Arc to maintain consistency

2024-01-24 14:48 UTC, nanderstabel commented on src-tauri/tests/tests/credential_offer.rs
> +use std::sync::Arc;
which tokio::Arc do you mean exactly?

2024-01-24 14:48 UTC, nanderstabel commented on src-tauri/identity_wallet/src/state/reducers/user_data_query.rs
> +            }) as Action,
will remove them

2024-01-24 15:36 UTC, daniel-mader approved these changes

2024-01-24 15:37 UTC, merged